// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../../styles/Home.module.css'
// import Link from 'next/link'

// export default function List({avatarsData}) {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Avatar Data</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Avatar Universe
//         </h1>

//         <div className={styles.grid}>
//             { 
//                 avatarsData.map(data => (
//                     <Link key={data._id} href={{ pathname: '/avatar/detail/[id]', query: { id: data._id } }}>
//                     <a className={styles.card} style={{margin: '50px'}}>
//                         <Image
//                             src={data.photoUrl}
//                             alt="avatar picture"
//                             width={500}
//                             height={500}
//                         />
//                         <h2>{data.name}</h2>
//                         <p>{ data.first != '' && data.first != '"' ? 
//                             (
//                                 data.first
//                             ):(null) 
//                             }
//                         </p>
//                     </a>
//                     </Link>
//                 ))
//             }
//         </div>
//       </main>

      
//     </div>
//   )
// }

// export async function getStaticProps() {
//     const res = await fetch('http://localhost:3000/api/avatars/list')
//     const avatarsData = await res.json()
  
//     return {
//       props: {
//         avatarsData,
//       },
//       // Next.js will attempt to re-generate the page:
//       // - When a request comes in
//       // - At most once every 10 seconds
//       revalidate: 10, // In seconds
//     }
// }

import React from 'react'

const List = () => {
  return (
    <div>List</div>
  )
}

export default List