import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import {avatar} from '../data'
import Card from '../components/Card/MuiCard'
import Grid from '@material-ui/core/Grid';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Avatar Data</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Avatar Universe
        </h1>

        {/* <div className={styles.grid}>
            { 
                avatar.map(data => (
                    <Link key={data._id} href={{ pathname: '/avatar/[id]', query: { id: data._id, name: data.name, position: data.position, gender: data.gender, profession: data.profession, image: data.photoUrl } }}>
                    <a className={styles.card} style={{margin: '50px'}}>
                        <Image
                            src={data.photoUrl}
                            alt="avatar picture"
                            width={500}
                            height={500}
                        />
                        <h2>{data.name}</h2>
                        <p>{ data.first != '' && data.first != '"' ? 
                            (
                                data.first
                            ):(null) 
                            }
                        </p>
                    </a>
                    </Link>
                ))
            }
        </div> */}
        { avatar && avatar.length > 0 ? (
            <Grid container spacing={2}>
            {
              avatar.map(data => (
                  <Card key={data._id} id={data._id} photoURL={data.photoUrl} name={data.name} first={data.first} position={data.position} gender={data.gender} profession={data.profession} />
              ))
            }
            </Grid>
          ) : (
            <p>Loading....</p>
          )
        }
      </main>

      
    </div>
  )
}
