import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import {avatar} from '../data'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Avatar Data</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Avatar Universe
        </h1>

        <div className={styles.grid}>
            { 
                avatar.map(data => (
                    <Link key={data._id} href={{ pathname: '/avatar/[id]', query: { id: data._id, name: data.name, position: data.position, gender: data.gender, profession: data.profession, image: data.photoUrl } }}>
                    <a className={styles.card} style={{margin: '50px'}}>
                        <Image
                            src={data.photoUrl}
                            alt="avatar picture"
                            width={500}
                            height={500}
                        />
                        <h2>{data.name}</h2>
                        <p>{ data.first != '' && data.first != '"' ? 
                            (
                                data.first
                            ):(null) 
                            }
                        </p>
                    </a>
                    </Link>
                ))
            }
        </div>
      </main>

      
    </div>
  )
}
