import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import dynamic from 'next/dynamic'
import React, { useState } from 'react'

const HelloComponent = dynamic(() => import('@/components/Hello'), {
  loading: () => <b style={{color:'#fff'}}>Loading....</b>,
});

export default function Home() {
  const [hello, setHello] = useState(null);
  // setHello(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Learn <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Training main page
        </p>

        <div className={styles.grid}>
          <Link href="/avatars">
            <a
              className={styles.card}
            >
              <h2>Avatars &rarr;</h2>
              <p>
                List of Avatar chars (read from direct file)
              </p>
            </a>
          </Link>
          <Link href="/avatar/list">
            <a
              className={styles.card}
            >
              <h2>Avatars &rarr;</h2>
              <p>
                List of Avatar chars (read from next API)
              </p>
            </a>
          </Link>
          
          <button style={{backgroundColor:'#fff'}} onClick={() => setHello(!hello)} className={styles.card}>
            {hello ? 'Hide' : 'Click Me' }
          </button>
          {
            hello ? <HelloComponent/> : null
          }
        </div>
      </main>
    </div>
  )
}
